export const RouteEnum = {
  OUR_SUPPORT: "/support",
  PRICING: "/pricing",
  BUSINESS_BANKING: "/business-banking",
  GLADE_POS: "/glade-pos",
  GLADE_STORE: "/glade-store",
  GLADE_PAY: "/glade-pay",
  SMALL_BUSINESS: "/small-business",
  FREELANCERS: "/freelancers",
  STARTUPS: "/startups",
  DASHBOARD_USER_MANUAL: "/dashboard-user-manual",
  MOBILE_USER_MANUAL: "/mobile-user-manual",
  GO_LIVE_GUIDE: "/go-live-guide",
  INVOICING_GUIDE: "/-nvoicing-guide",
  PAY_ME_LINK: "/pay-me-link-guide",
  MAKE_PAYMENTS_GUIDE: "/make-payments-guide",
  FAQ: "/faq",
  ABOUT_US: "/about-us",
  CONTACT_US: "/contact-us",
  BLOG: "/blog",
};
